<a href="https://colab.research.google.com/github/dikshasaraswa/Build-an-ANN-Regression-Model/blob/main/ANNelectricalenergy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Artificial Neural Network**

**Importing the Libraries**

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.17.0'

# **Part-1 Data Processing**




**Importing the Dataset**

In [4]:
dataset = pd.read_excel('/content/Folds5x2_pp.xlsx')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(x)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


**Splitting the Dataset into Training set and Test set**

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

# **Part 2 - Building the ANN**

**Initializing the ANN**

In [7]:
ann = tf.keras.models.Sequential()

 **Adding the input layer and the first hidden layer**

In [8]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

 **Adding the second hidden layer**

In [9]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

**Adding the output layer**

In [10]:
ann.add(tf.keras.layers.Dense(units = 1))

# **Part-3 Training the ANN**

**Compiling the ANN**

In [11]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

**Training the ANN model on the Training set**

In [12]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 276193.3750
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 206257.8125
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 206244.3594
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 206035.7500
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 205728.0781
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 205727.3438
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 205154.0938
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 204765.3125
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 204928.4062
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 204631.1406
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 204699.7344
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 204291.0000
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 203851.1719
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1m

**Predicting the results of Test set**

In [13]:
y_pred = ann.predict(x_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))


60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[ 23.91 431.23]
 [ 23.91 460.01]
 [ 23.91 461.14]
 ...
 [ 23.91 473.26]
 [ 23.91 438.  ]
 [ 23.91 463.28]]
