<a href="https://colab.research.google.com/github/dikshasaraswa/Build-an-ANN-Regression-Model/blob/main/ANNelectricalenergy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Artificial Neural Network**

**Importing the Libraries**

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.17.0'

# **Part-1 Data Processing**




**Importing the Dataset**

In [ ]:
dataset = pd.read_excel('/content/Folds5x2_pp.xlsx')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


**Splitting the Dataset into Training set and Test set**

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

# **Part 2 - Building the ANN**

**Initializing the ANN**

In [ ]:
ann = tf.keras.models.Sequential()

 **Adding the input layer and the first hidden layer**

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

 **Adding the second hidden layer**

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

**Adding the output layer**

**Compiling the ANN**